### ISSUE TITLE
Output pointcloud that can be recognized as from a projective device?

### ISSUE THREAD

**Issue by sloretz** [lovepark/o3d3xx-ros#21]
How do I get a point cloud from an o3d303 camera that PCL can recognize as from a projective device?

I'm trying to use the nodelet pcl/StatisticalOutlierRemoval on the output of a point cloud from an o3d303 camera. PCL complains that the cloud is not from a projective device. It says this:
```
[pcl::OrganizedNeighbor::radiusSearch] Input dataset is not from a projective device!
  Residual (MSE) 0.000133, using 1188 valid points
```

The definition of a projective device is [here](http://www.pcl-users.org/Definition-of-a-Projective-Device-td4018681.html)

**Comment by tpanzarella** [comment]
I have never run into this before, however, I have used the `StatisticalOutlierRemoval` filter numerous times with `o3d3xx-ros` without issue. To that end, in order to try to help, two things would be very helpful:

1. Please attach or paste in a *minimal code example* that can be used to reproduce the issue.
2. It would be useful to see what the cloud looks like at the time of getting the error. You could either take an `rviz` (or `o3d3xx-viewer`) screen shot and paste that in, or, attach a PCD.

**Comment by sloretz** [comment]
Hi Tom,

I updated libo3d3xx and o3d3xx-ros to the latest commits on master and I'm no longer seeing the issue.

Thanks for your time.
