### ISSUE TITLE
Extrinsics not latched

### ISSUE THREAD

**Issue by bsbc** [lovepark/o3d3xx-ros#22]
We are using /o3d3xx/camera/extrinsics and /o3d3xx/camera/unit_vectors for ray-tracing.

We noticed that the unit_vectors are published once (i.e. latched) but the extrinsics are published continuously.

We were wondering why this is happening. Is it possible that the extrinsincs change during operation / after camera (factory) calibration?

**Comment by bsbc** [comment]
Additionally: could you please confirm that the rotation part of the extrinsics are already included in the unit_vectors, thereby we (@bibarz) can ignore those when converting depth to point-cloud?

**Comment by tpanzarella** [comment]
The extrinsics could change, as the camera exposes a user-supplied extrinsic calibration via the XML-RPC interface. Technically the extrinsics could only be sent once, just like the rotated unit vectors, but at the time of implementation considering the extrinsics as an invariant on the schema seemed cheap given that it is only 6 floats. However, the unit vectors were considered expensive for obvious reasons.

Per your second comment, yes, the unit vectors are already rotated. You can see this validated via the unit test code for `libo3d3xx` (the underlying driver to this ros interface). [This](https://github.com/lovepark/libo3d3xx/blob/master/modules/image/test/o3d3xx-image-tests.cpp#L535) and [this](https://github.com/lovepark/libo3d3xx/blob/master/modules/image/test/o3d3xx-image-tests.cpp#L347) would probably be a helpful reference/validation.

**Comment by tpanzarella** [comment]
I should note that there is a ROS/Python version for doing what you want to do implemented in the `o3d3xx-ros` unit test. That test code is [here](https://github.com/lovepark/o3d3xx-ros/blob/master/test/test_camera.py#L100)

**Comment by tpanzarella** [comment]
Finally, I see no issue with latching the extrinsics. Even though we are streaming it continuously from the camera, there is no need to have continuous callbacks running in your ROS node -- you make a good point. If you want to submit a PR for that (against the HEAD) that would be appreciated. If not, we can leave this issue open and I'll get to doing that when I have the time.

**Comment by tpanzarella** [comment]
OK, one last point we should consider here.... I now remember why we chose to stream the extrinsics constantly from the camera *and* also publish them continuously in ROS. 

Basically, the `libo3d3xx` driver, at the time of image acquisition, transforms the delivered point cloud from the camera into a standard ROS coord frame (+x forward, +y left, +z up). If you make the assumption there is no user-supplied extrinsic calibration applied to the camera (i.e., the XML-RPC/JSON dump reports 0,0,0,0,0,0), you can get the first value of the extrinsics and use this as a reference (it will not be all zeros because this contains the transform from the imager chip to the camera glass). Then you can check each subsequent extrinsics message to make sure that it has not changed from the reference values (i.e., in a different thread, command-line tool, etc.). If they have changed, you really cannot trust any of the Cartesian data as (0,0,0,0,0,0) assumption made by the driver is violated and all bets are off.

**Comment by bsbc** [comment]
According to this, the unit_vectors should be changed when/if the extrinsics change. ?

**Comment by bsbc** [comment]
Thanks for resolving/answering our questions so quickly.
(The issue can be closed)

**Comment by tpanzarella** [comment]
> According to this, the unit_vectors should be changed when/if the extrinsics change. ?

Yes. But really, if the extrinsics change, it should be considered an error unless you really know what you are doing (it sounds like you do).


> Thanks for resolving/answering our questions so quickly.
> (The issue can be closed)

No problem. Good luck and have a nice weekend.
