### ISSUE TITLE
Compiling o3d3xx-ros

### ISSUE THREAD

**Issue by waalbukhanajer** [lovepark/o3d3xx-ros#40]
Hi guys,

I have a IFM O3D302 ToF camera and wanted to install ros drivers. After I installed all the required libraries, and went through several issues (from my end), I am stuck now with the following error when I catkin_make my workspace.

I updated the firmware to the latest, installed modules within libo3d3xx correctly (image, camera, pcicclient, framegrabber) and i am running Ubuntu 14.04 and ROS indigo, pcl 1.7

i tried to uninstall opencv completely and reinstall only what is required by this package for ros opencv (i.e., cv-bridge, image-transport, camera-info-manager).

Any help/ suggestion is highly appreciated 

/usr/bin/ld: warning: libopencv_core.so.3.2, needed by /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libo3d3xx_image.so, may conflict with libopencv_core.so.2.4
/usr/bin/ld: CMakeFiles/o3d3xx_node.dir/src/o3d3xx_node.cpp.o: undefined reference to symbol '_ZN2cv6String10deallocateEv'
//usr/local/lib/libopencv_core.so.3.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [/home/efmzafra/Development/hyg_ida/devel/lib/o3d3xx/o3d3xx_node] Error 1
make[1]: *** [o3d3xx-ros/CMakeFiles/o3d3xx_node.dir/all] Error 2
make: *** [all] Error 2
Invoking "make -j8 -l8" failed

**Comment by tpanzarella** [comment]
It appears as though you have both OpenCV 3 and OpenCV 2.4 installed on your system. Since you are using ROS Indigo and you want to build our ROS bindings, you will need to settle on using OpenCV 2.4. I.e., you cannot link to two different versions of OpenCV in the same bindary. From the above output, it looks like when you built `libo3d3xx`'s image module you linked to OpenCV 3. When building the image module of `libo3d3xx` you can specify the `-DFORCE_OPENCV2=ON` flag to ensure you are building against OpenCV 2.4. Please note, this will require you to*not* use the top-level build system in `libo3d3xx` but rather build each module individually.

An unrelated note, but worth bringing up.... if you are just getting started with the ifm O3 cameras, I'd suggest you consider using the newer libraries: [ifm3d](https://github.com/lovepark/ifm3d) and [ifm3d-ros](https://github.com/lovepark/ifm3d-ros).

**Comment by waalbukhanajer** [comment]
Hi Tom,
Thanks a lot for help. The issue now is resolved, as following:
1- I found references to opencv 3 (was installed from source) and removed it using sudo make uninstall. And deleted the previous 'build' folders from each modules and the libo3d3xx. 
2- I rebuild the individual modules, camera, framegrabber
3- build the image module with -DFORCE_OPENCV2=ON flag 
4- build the top-level library with camera connected. (at first (i.e., before deleting the 'build' folders and rebuild again with -DFORCE_OPENCV2=ON for image module), the catkin_make failed as libopencv_core.so.3 says missing and still needed by libo3d3xx). resolved when I started again by deleting the 'build' folders. 
5- catkin_make my workspace
All Tests are passed. and now I can start rviz and view the data.

Thanks again
Wissam
